### ISSUE TITLE
Empty Evernote syncronised notes

### ISSUE THREAD

**Issue by theotix** [aniket-deole/notes#32]
Your app is so great,
but my problem is, after sync my Evernote's notes, all of them are empty.
Do you have an idea ?
![141728](https://cloud.githubusercontent.com/assets/2143796/9761850/7ca33630-56ff-11e5-837e-c4b069d36452.png)
http://theoti.me/i/142842.png
(Installed on ElementaryOS (based on Ubuntu 14.04)

**Comment by aniket-deole** [comment]
Yes. I tried implementing a Full sync, but the due to the Evernote API Rate limits, everything stops working if you have a lot of notes as it does a lot of calls to fetch all the notes, images and attachments.
So, I'm still in the process of thinking which notes to sync during first login, and how to handle incremental sync.
I would like some comments & feedback on this point as well.

Points i have thought about:
During First Sync:
1. Sync all note headers like the above screenshot. 
2. Sync note bodies of only the latest 10 notes. 
3. Sync the rest of the note bodies as and when required.
If I implement this, then the Search feature might be a bit wonky, as it will only search the latest 10 notes & I will have to use the Evernote Search API.

OR
Periodically keep syncing note bodies, until we have all the note bodies. This might take 2 days (for ~500 notes) for a full sync to happen, as Evernote imposes hourly rate limits.

**Comment by vivekbhalla** [comment]
I don't know much about it but you must have checked this obviously https://dev.evernote.com/doc/articles/rate_limits.php
The Initial Sync Boost thing doesn't work either?

**Comment by aniket-deole** [comment]
Last time i checked, the Initial Sync boost thing was not there.
I'll give it a go! Thanks.
